@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant Build
participant Server
database AppState
actor Client

== Build Tools ==

note over Build #8fe68f: currentVersion="8fe68f"
Build -> Server: deployment

hnote over Build: Repository Updates

Build --> Build: define currentVersion by glob-hashing\n    storage-related files / folders

rnote over Build #fff: currentVersion inferred from\ncontents of storage-related files\ne.g.:

alt changes in storage-related files / folders
|||
    note over Build #ffd18a: currentVersion="ffd18a"
    note over Build #a3e8f9: currentVersion="a3e8f9"
    rnote over Build #fff: etc pp. Also considers a \'".version\'" file
    Build -> Server: deployment
|||
else no changes in storage-related files / folders
|||
    note over Build #8fe68f: currentVersion="8fe68f"
    Build -> Server: deployment
|||
end

==  ==

Client -> Server: GET /

activate Client

Server --> Client: Bundle contains\ncurrentVersion

== TidyStorage Promise ==

Client -> AppState: getVersion ( )
AppState --> Client: cachedVersion

Client -> Client: isLatestVersion?\ntrue if currentVersion === cachedVersion

alt isLatestVersion === true
|||
else isLatestVersion === false
|||
   Client -> AppState: clearAppStorage ( )
   Client -> AppState: setVersion ( currentVersion )
end
|||

deactivate Client

== TidyStorage Promise fulfilled ==

@enduml
